=== gasfet/C-Programming-Bible-with-.Net-framework-3.0/소스코드/ch11/XmlReaderSettingsExam/XmlReaderSettingsExam/bin/Debug/song.dtd
<!ELEMENT songdata (song)*>
<!ELEMENT song (title, singer, year)>
<!ATTLIST song genre CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT singer (#PCDATA)>
<!ELEMENT year (#PCDATA)>

=== gasfet/C-Programming-Bible-with-.Net-framework-3.0/소스코드/ch11/songdtd.xml
<?xml version="1.0" encoding="euc-kr" ?>
<!DOCTYPE songdata SYSTEM "song.dtd">
<!-- songdata list -->
<songdata>
  <song genre="ballade">
    <title>아름다운세상</title>
    <singer>박학기</singer>
    <year>1990</year>
  </song>
  <song genre="rock">
    <title>슈퍼스타</title>
    <singer>러브홀릭</singer>
    <year>2003</year>
  </song>
</songdata>
